### ISSUE TITLE
hyperloop module sources

### ISSUE THREAD

**Issue by farfromrefug** [appcelerator/titanium_mobile#10004]
would it be possible to have access to the hyperloop module sources? I am testing the very last version of titanium v8. but then hyperloop module work because it needs to be rebuilt with the latest krollv8 for it to work. sadly i can't do that without the sources. 
I did not find the sources on github. is it closed source ?
thanks

**Comment by hansemannn** [comment]
Hey there! Hyperloop is closed source as of for now. There will be a recompiled version once the V8 changes are starting to be integrated into master, since all Hyperloop releases are built by the Jenkins CI which uses master to build all modules. If you want to dive deeper into V8 and the Titanium V8 relation, let us know!

**Comment by farfromrefug** [comment]
@hansemannn that's what i thought. And if i am correct this is because of the licensing thing of hyperloop?
Could that part be made into a jar/.a file so that the module could become open source?
What do you mean by dive deeper into v8? You mean help? I am actually trying to right now. I have started commenting on the latest changes in v8 and looking at how to improve it. I really want to help

**Comment by hansemannn** [comment]
Love the input, thank you @farfromrefug! I'm pretty sure @sgtcoolguy will let you know his thoughts in the V8 PR. Thanks again!
