### ISSUE TITLE
Ti SDK 9.3.2GA Android camera image not working (image.toBlob())

### ISSUE THREAD

**Issue by arunraj-qburst** [appcelerator/titanium_mobile#12819]
### Describe the bug
Implement the camera as Ti.Media.showCamera(........)
Up on getting the response.media assign it into ImageView
Using ti.imagefactory it is resizing the image data.
Image data is loaded to an ImageView component.
Get a image.toBlob() 
after this line of code the data is not getting (Only with Android )
 
### Expected behavior
Image data should be available as blob

### Environment
Titanium SDK version:  9.3.2GA
CLI version: 8.1.1

This is working fine if i use Ti SDK 8.3.1GA as it will ask for a popup for providing the storage permission. But not with the Ti 9.3.2

In The manifest file:
```

 <manifest android:versionCode="89" android:versionName="5.0.0">
            <uses-sdk android:minSdkVersion="23" android:targetSdkVersion="29"/>
<uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
            <uses-permission android:name="android.permission.MANAGE_MEDIA"/>
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
.....
....
<application   android:requestLegacyExternalStorage="true" 

```

**Comment by m1ga** [comment]
can you show the code parts? It is a bit confusing what `image` is at the end of your description. So all the imageviews display the correct image? What do you want to do with the last `toBlob`? So since you can resize it and display it there is no issue in the camera, so the issue title is misleading.

Also do you ask for runtime permissions `Ti.Android.requestPermissions`? You'll need those instead of the tiapp.xml permissions.

**Comment by ewanharris** [comment]
As m1ga states, please provide code here as it's quite a complex description you gave. I'm going to close this out due to inactivity, but if the issue still occurs please open a new issue with reproducible code
