### ISSUE TITLE
Ti.App.arguments doesn't work.

### ISSUE THREAD

**Issue by jasonkneen** [appcelerator/titanium_mobile#12945]
Documentation is saying to use `Ti.App.arguments` instead of `Ti.App.getArguments()` yet this doesn't work and is never populated.

**Comment by jquick-axway** [comment]
I've confirmed this to be a regression in Titanium 10.0.0.
PR #12956 fixes it. The plan is to fix this issue in Titanium 10.0.1.
Thanks for reporting it.

**Comment by jasonkneen** [comment]
Can we backport it to 9.3.2.ga?

**Comment by jquick-axway** [comment]
> Can we backport it to 9.3.2.ga?

I don't plan to. We've never supported the `Ti.App.arguments` property before Titanium 10.x.x. That was a documentation error. This property was intended to be added to 10.0.0 but that didn't actually happen (it will be added to 10.0.1). I did resurrect the `getArguments()` method for Titanium 10.0.1 since that was the only API available before.
